In [36]:
import pandas as pd
import numpy as np 

from sklearn.preprocessing import OneHotEncoder,LabelEncoder,MinMaxScaler,StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split

Filling empty values with mean of column

In [26]:
df = pd.read_csv("https://raw.githubusercontent.com/akvdkharnath/My-Research/master/Python%20Files/Data/Data.csv")
df = df.fillna(df.mean())
df

   Country        Age        Salary Purchased
0   France  44.000000  72000.000000        No
1    Spain  27.000000  48000.000000       Yes
2  Germany  30.000000  54000.000000        No
3    Spain  38.000000  61000.000000        No
4  Germany  40.000000  63777.777778       Yes
5   France  35.000000  58000.000000       Yes
6    Spain  38.777778  52000.000000        No
7   France  48.000000  79000.000000       Yes
8  Germany  50.000000  83000.000000        No
9   France  37.000000  67000.000000       Yes

split input and output data

In [30]:
x = df.iloc[:,:-1]
y = df.iloc[:,-1]
print(x)
print(y)

   Country        Age        Salary
0   France  44.000000  72000.000000
1    Spain  27.000000  48000.000000
2  Germany  30.000000  54000.000000
3    Spain  38.000000  61000.000000
4  Germany  40.000000  63777.777778
5   France  35.000000  58000.000000
6    Spain  38.777778  52000.000000
7   France  48.000000  79000.000000
8  Germany  50.000000  83000.000000
9   France  37.000000  67000.000000
0     No
1    Yes
2     No
3     No
4    Yes
5    Yes
6     No
7    Yes
8     No
9    Yes
Name: Purchased, dtype: object

**One Hot Encodeing:**

used to encode cetogorical values in to many columns 
ColumnTransformer -->

transformers --> [(encoding method,function,[columns to apply])]

remainder --> if passthrough it will result onehotencoded columns + other columns, if drop then only return onehotencoded columns

In [31]:
ct = ColumnTransformer(transformers=[("encoder",OneHotEncoder(),[0])],remainder="passthrough")
x = np.array(ct.fit_transform(x),dtype=str)
x = pd.DataFrame(x)
print(x)

     0    1    2                  3                  4
0  1.0  0.0  0.0               44.0            72000.0
1  0.0  0.0  1.0               27.0            48000.0
2  0.0  1.0  0.0               30.0            54000.0
3  0.0  0.0  1.0               38.0            61000.0
4  0.0  1.0  0.0               40.0  63777.77777777778
5  1.0  0.0  0.0               35.0            58000.0
6  0.0  0.0  1.0  38.77777777777778            52000.0
7  1.0  0.0  0.0               48.0            79000.0
8  0.0  1.0  0.0               50.0            83000.0
9  1.0  0.0  0.0               37.0            67000.0

**Label Encoding:**

used to encode a cetogorical values into numarical values 

difference between OneHot Encoding and Label Encoding
OneHot is used to encode cetogorical column into mutiple columns but Label encoder is used to encode cetogorical column into singlr column

In [32]:
le = LabelEncoder()
y = np.array(le.fit_transform(y))
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

**Split data into Train and Test**

its better to have data in 8:2 ratio

In [39]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.8)

**Scaling:**

1. Normalization
    1. converts data into 0 to 1 
    2. use MinMaxscaler to apply
    3. apply only if data is in Normal/ Gaussion distribution

2. Standradization
    1. converts data from -3 to +3 
    2. use StandardScaler to apply 
    3. can apply for all most all data

**Note:** pls dont apply scaling for One hot encoded data

In [43]:
sc = StandardScaler()
x_train.iloc[:,3:] = sc.fit_transform(x_train.iloc[:,3:])
x_test

/usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

     0    1    2                  3                  4
4  0.0  1.0  0.0               40.0  63777.77777777778
5  1.0  0.0  0.0               35.0            58000.0
3  0.0  0.0  1.0               38.0            61000.0
1  0.0  0.0  1.0               27.0            48000.0
6  0.0  0.0  1.0  38.77777777777778            52000.0
8  0.0  1.0  0.0               50.0            83000.0
7  1.0  0.0  0.0               48.0            79000.0
2  0.0  1.0  0.0               30.0            54000.0